name: Deploy to GitHub Pages

on:
  push:
    branches:
      - model-viewer  # This ensures the action only runs on this branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: model-viewer # Explicitly checkout the correct branch
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './www' # Your subdirectory
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4